# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

# Shared secrets are available across all environments.

# shared:
#   api_key: a1B2c3D4e5F6

# Environmental secrets are only available for that specific environment.

development:
  secret_key_base: c73e73893fee891831fda711f0c72717ef6dd3101578a4f3198ac4271149776cf4fd3f2dc907db4c3c9296a95059a05ed1478ac1094b495885c3162dc1a4a169

test:
  secret_key_base: 3e7d59f6096c6ddfb6deffd8c8a94f34892beb1196b3e51ff75e74b4561113c28932344613be3b5cc7e97e1b7583a8c504bf4cbce037e3ae6fa33352b3da94a9

# Do not keep production secrets in the unencrypted secrets file.
# Instead, either read values from the environment.
# Or, use `bin/rails secrets:setup` to configure encrypted secrets
# and move the `production:` environment over there.

production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
